// Build script: embeds web/ assets into worker/src/web-assets.ts as strings.
// Run before deploy:  node scripts/embed-web.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");          // repo root
const webDir = join(root, "web");
const out = join(root, "worker", "src", "web-assets.ts");

function lit(name) {
  const raw = readFileSync(join(webDir, name), "utf8");
  // JSON.stringify produces a safe double-quoted JS string literal.
  return JSON.stringify(raw);
}

const banner = "// AUTO-GENERATED by scripts/embed-web.mjs — do not edit by hand.\n";
const body =
  `export const INDEX_HTML = ${lit("index.html")};\n` +
  `export const INSTALL_SH = ${lit("install.sh")};\n` +
  `export const INSTALL_PS1 = ${lit("install.ps1")};\n` +
  `export const LAUNCHER_PY = ${lit("launcher.py")};\n`;

writeFileSync(out, banner + body);
console.log(`embedded web assets → ${out}`);
